### PR TITLE
Introducing StartChildBySpec/StopChildByName

### PR DESCRIPTION
**Pull request by leonlee2013**
Introducing StartChildBySpec/StopChildByName to dynamically add and remove child specifications.

### CODE REVIEW

**Comment by rupurt** [comment]
@leonlee2013 I like where you're going with this. Creating a supervisor with a dynamic number of workers is cumbersome atm. @halturin are there any specific reasons the API doesn't map to Erlang [supervisor#start_child](https://www.erlang.org/doc/man/supervisor.html#start_child-2)?

For consistency with Erlang I feel like the current `gen.Supervisor#StartChild` function should take a spec. The existing implementation doesn't look like it's used internally. It could be achieved by adding the Erlang implementation for [get_childspec](https://www.erlang.org/doc/man/supervisor.html#get_childspec-2).

**Comment by halturin** [comment]
@leonlee2013 I would prefer to see this proposal as a discussion rather than PR. 

https://github.com/ergo-services/ergo/blob/master/CONTRIBUTING.md#submitting-pull-requests

**Comment by leonlee2013** [comment]
@halturin OK, got it. Do you need me to close the PR and move it to the discussions?

**Comment by leonlee2013** [comment]
@halturin I moved the PR to [the discussion forum](https://github.com/ergo-services/ergo/discussions/142) .

**Comment by halturin** [comment]
Implemented in the coming 3.0 (scheduled to release this fall)

**Pull request closed without merging**
