### PR TITLE
version 3.0.0

### PR DESCRIPTION
**Pull request by halturin**
Completely redesigned and written from scratch.
Erlang support is moved to a separate package.

### CODE REVIEW

**Comment by autodidaddict** [comment]
Is this something we can/should play with now, or is it still pretty volatile?

**Comment by halturin** [comment]
> Is this something we can/should play with now, or is it still pretty volatile?

sure. mostly some polishing inside. its stable now. anyway, if you find something, feel free to report. But Erlang is removed to the external package and in active development now (in github.com/ergo-services/proto/erlang). Worth to mention, it will be distibuted under BSL license.

PS: you may want to try "events" in version 3.0. Its a distributed pub/sub. See "RegisterEvent" and "LinkEvent/MonoitorEvent" methods.

**Comment by halturin** [comment]
@autodidaddict  forgot to mention, see `examples` repo (v300 branch) to take inspiration. another great tool for the v.3.0.0 is  `observer` (tools/observer in v300 branch) https://x.com/halturin/status/1776279572826234965?s=46&t=a-KSHQlLDlsyfI8bjFDfng

**Comment by autodidaddict** [comment]
> @autodidaddict forgot to mention, see `examples` repo (v300 branch) to take inspiration. another great tool for the v.3.0.0 is `observer` (tools/observer in v300 branch) https://x.com/halturin/status/1776279572826234965?s=46&t=a-KSHQlLDlsyfI8bjFDfng

that looks amazing!

**Comment by Tochemey** [comment]
@halturin nice job on this journey and respect. I know how hard it is to keep maintaining open source tool. You are an inspiration to me. Chapeau 🎩

**Comment by halturin** [comment]
scheduled for Sep 4 🤞

**Pull request merged**
